export const PAGE_VIEW = 'PAGE_VIEW'
export const CLICK = 'CLICK'
export const SEARCH = 'SEARCH'
export const VIDEO_PLAY = 'VIDEO_PLAY'
export const VIDEO_PAUSE = 'VIDEO_PAUSE'
export const VIDEO_COMPLETE = 'VIDEO_COMPLETE'
export const QUIZ_START = 'QUIZ_START'
export const QUIZ_SUBMIT = 'QUIZ_SUBMIT'
export const COURSE_OPEN = 'COURSE_OPEN'
export const SESSION_START = 'SESSION_START'
export const SESSION_END = 'SESSION_END'
export const CERTIFICATE_GENERATED = 'CERTIFICATE_GENERATED'
export const CERTIFICATE_VIEWED = 'CERTIFICATE_VIEWED'
export const CERTIFICATE_DOWNLOADED = 'CERTIFICATE_DOWNLOADED'
export const CERTIFICATE_SHARED = 'CERTIFICATE_SHARED'
export const LESSON_STARTED = 'LESSON_STARTED'
export const LESSON_COMPLETED = 'LESSON_COMPLETED'
export const LESSON_MARKED_COMPLETE = 'LESSON_MARKED_COMPLETE'
export const COURSE_COMPLETION_PERCENTAGE = 'COURSE_COMPLETION_PERCENTAGE'
export const TIME_SPENT_LEARNING = 'TIME_SPENT_LEARNING'

export const EVENT_TYPES = [
  PAGE_VIEW,
  CLICK,
  SEARCH,
  VIDEO_PLAY,
  VIDEO_PAUSE,
  VIDEO_COMPLETE,
  QUIZ_START,
  QUIZ_SUBMIT,
  COURSE_OPEN,
  SESSION_START,
  SESSION_END,
  CERTIFICATE_GENERATED,
  CERTIFICATE_VIEWED,
  CERTIFICATE_DOWNLOADED,
  CERTIFICATE_SHARED,
  LESSON_STARTED,
  LESSON_COMPLETED,
  LESSON_MARKED_COMPLETE,
  COURSE_COMPLETION_PERCENTAGE,
  TIME_SPENT_LEARNING,
]
