export const EVENT_TYPES = {
  PAGE_VIEW: 'page_view',
  CLICK: 'click',
  SEARCH: 'search',
  COURSE_OPEN: 'course_open',
  VIDEO_PLAY: 'video_play',
  VIDEO_PAUSE: 'video_pause',
  VIDEO_COMPLETE: 'video_complete',
  QUIZ_START: 'quiz_start',
  QUIZ_SUBMIT: 'quiz_submit',
  SESSION_START: 'session_start',
  SESSION_END: 'session_end',
  DASHBOARD_OPEN: 'dashboard_open',
  FILTER_CHANGE: 'filter_change',
  REPORT_DOWNLOAD: 'report_download',
  EXPORT_CSV: 'export_csv',
  EXPORT_JSON: 'export_json',
  PRINT_REPORT: 'print_report',
};
